<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SSO"
           tests="6"
           failures="1"
           errors="0"
           skipped="4"
           time="0.187">
  <properties />
            <testcase name="afterTest" time="0.000" classname="com.ezijing.qa.datacenter.GetCourseInformation">
                <failure type="java.lang.AssertionError"
                  message="expected:&lt;1009&gt; but was:&lt;200&gt;"
              >
<![CDATA[java.lang.AssertionError: expected:<1009> but was:<200>
  org.junit.Assert.fail(Assert.java:88)
  org.junit.Assert.failNotEquals(Assert.java:743)
  org.junit.Assert.assertEquals(Assert.java:118)
  org.junit.Assert.assertEquals(Assert.java:555)
  org.junit.Assert.assertEquals(Assert.java:542)
  com.ezijing.qa.sso.PostTickets.afterTest(PostTickets.java:135)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:130)
  org.testng.TestRunner.afterRun(TestRunner.java:1187)
  org.testng.TestRunner.run(TestRunner.java:612)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
  org.testng.TestNG.run(TestNG.java:999)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
  org.apache.maven.surefire.Surefire.run(Surefire.java:177)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
  org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
]]>
      </failure>

          </testcase>
  
            <testcase name="afterTest" time="0.0" classname="com.ezijing.qa.datacenter.GetCourseInformation">
          <skipped />
    </testcase>
            <testcase name="deleteUser" time="0.0" classname="com.ezijing.qa.datacenter.GetCourseInformation">
          <skipped />
    </testcase>
            <testcase name="afterTest" time="0.0" classname="com.ezijing.qa.datacenter.GetCourseInformation">
          <skipped />
    </testcase>
            <testcase name="deleteUser" time="0.0" classname="com.ezijing.qa.datacenter.GetCourseInformation">
          <skipped />
    </testcase>
  
            <testcase name="courseInformation" time="0.187" classname="com.ezijing.qa.datacenter.GetCourseInformation" />
      
</testsuite>
